GET https://bootcamp-api.codeit.kr/api/users
Authorization: eyJhbGciOiJIUzI1NiIsImtpZCI6IktLNE05TGFmMXkzWEI0M0kiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEzNDMwODEzLCJpYXQiOjE3MTI4MjYwMTMsImlzcyI6Imh0dHBzOi8vanB2ZG9weWdibHJlZnpvbmV2ZnEuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjE1YjZiMzVlLTVkNjUtNGUxMS1iMmViLTA0OWZkNWZhMjA5NyIsImVtYWlsIjoid2tycmhyQGVocmdrci5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoid2tycmhyQGVocmdrci5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMTViNmIzNWUtNWQ2NS00ZTExLWIyZWItMDQ5ZmQ1ZmEyMDk3In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTI4MjYwMTN9XSwic2Vzc2lvbl9pZCI6IjBiYzY0N2JkLTJlMTMtNDA0YS04NTliLTA3NzZjZjkyNzYzZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.-Mdk1yZZUoT7md40aQQ3DPIc1cufXNOwSCTxUb2H7oY
