import Head from "next/head";
import Link from "next/link";

export default function Home() {
	return (
		<>
			<Head>
				<title>Linkbrary</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Link href="/shared">/shared</Link>
			<br />
			<Link href="/folder">/folder</Link>
			<br />
			<Link href="/signin">/signin</Link>
			<br />
			<Link href="/signup">/signup</Link>
			<br />
		</>
	);
}
